[profile.default]
src = 'src/'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path = 'forge-cache/sol'
optimizer = true
optimizer_runs = 100
via_ir = false
solc_version = '0.8.9'
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
    '@uniswap/v2-core/=node_modules/@uniswap/v2-core/contracts',
    '@uniswap/lib/=node_modules/@uniswap/lib/contracts',
]

[profile.yul]
src = 'yul'
out = 'out/yul'
libs = ['node_modules', 'lib']
cache_path = 'forge-cache/yul'
remappings = []
auto_detect_remappings = false

[fmt]
number_underscore = 'thousands'
line_length = 100

[fuzz]
runs = 5000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
